version: '3.9'

services:
  #MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:5.0
    restart: always
    ports:
      - 2717:2717
    volumes:
      - mongo_db:/data/db
  #Node API service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017/chwdb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}